[projects]

  [projects.default]
  contents = [
    "dedicatoria",
    "prefacio",
    "agradecimientos",
    "introduccion",
    "primer_modelo_matematico",
    "planificacion_produccion",
    "apendices",
    "references",
  ]

  # Full URL, required for the sitemap and robots.txt.
  online_url = "https://booktemplate.huijzer.xyz"

  # Extra directories to be copied.
  extra_directories = []

  # Port used by serve()
  port = 8004

  output_filename = "libroOptimizacion"
